version: '3.8'
services:
  glances:
    container_name: glances
    hostname: SERVER-MON
    restart: unless-stopped
    ports:
      - '61208:61208'
    environment:
      - GLANCES_OPT=-w
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    pid: host
    image: 'nicolargo/glances:latest'