version: '3.8'
services:
  home-assistant:
    container_name: home-assistant
    volumes:
      - '/home/kevin/Dockervolumes/home-assistant/:/config'
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    restart: unless-stopped
    build:
      context: ./home-assistant
    env_file:
      - ./home-assistant/secrets.env