version: '3.8'
services:
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /home/kevin/Dockervolumes/grocy/:/config
    ports:
      - 9283:9283
    restart: unless-stopped