version: '3.8'
services:
  uptime-kuma:
    restart: unless-stopped
    ports:
        - '3001:3001'
    volumes:
        - '/home/kevin/Dockervolumes/uptime-kuma/:/app/data'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:1'