version: '3.8'
services:
  deconz:
    container_name: deconz
    image: marthoc/deconz
    privileged: true
    environment: 
      - TZ=Europe/Oslo
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=4430
    volumes: 
      - /home/kevin/Dockervolumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2231183-if00:/dev/ttyUSB0
    ports:
      - 8080:8080
      - 4430:4430
    restart: unless-stopped
