- id: '1637497305401'
  alias: Sunset turn on some lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.corner_lamp
      - light.color_temperature_light_11
    data:
      brightness_pct: 100
      transition: 10
  mode: single
- id: '1637497527983'
  alias: 23:00, turn on lights sleep mode
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.adaptive_lighting_sleep_mode_all_lights
  mode: single
- id: '1637598552629'
  alias: Sunrise, turn off night light and light sleep mode
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.color_temperature_light_11
    data: {}
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.adaptive_lighting_sleep_mode_all_lights
  mode: single
- id: '1637599717618'
  alias: Morning alarm
  description: Bedroom lights and radio to wake up
  trigger:
  - platform: time
    at: 06:00
    id: Early
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen_speaker
    data:
      media_content_id: http://lyd.nrk.no/nrk_radio_klassisk_mp3_h
      media_content_type: channel
  - service: light.turn_on
    target:
      entity_id: light.color_temperature_light_14
    data:
      brightness_pct: 50
      kelvin: 6500
  - service: script.turn_on_some_things
    data: {}
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments:
      - 5
    target:
      entity_id: vacuum.dreame
    alias: Vacuum bedroom
    enabled: false
  mode: single
- id: '1637607890866'
  alias: Switch Office Off
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_office_off
    event_data:
      id: dimmer_switch_office
      event: 4000
  condition: []
  action:
  - type: turn_off
    device_id: a88c31e33af2f4c62bf180b8b5dfbd86
    entity_id: light.color_temperature_light_15
    domain: light
  mode: single
- id: '1637607982481'
  alias: Switch Office Dim Up
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_office_dim_up
    event_data:
      id: dimmer_switch_office
      event: 2000
  condition: []
  action:
  - device_id: a88c31e33af2f4c62bf180b8b5dfbd86
    domain: light
    entity_id: light.color_temperature_light_15
    type: brightness_increase
  mode: single
- id: '1637608013545'
  alias: Switch Office Dim Down
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_office_dim_down
    event_data:
      id: dimmer_switch_office
      event: 3000
  condition: []
  action:
  - device_id: a88c31e33af2f4c62bf180b8b5dfbd86
    domain: light
    entity_id: light.color_temperature_light_15
    type: brightness_decrease
  mode: single
- id: '1637608281691'
  alias: Switch Office On
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_office_on
    event_data:
      id: dimmer_switch_office
      event: 1000
  condition: []
  action:
  - service: light.turn_on
    data:
      kelvin: 2700
      brightness_pct: 100
    target:
      entity_id: light.color_temperature_light_15
  mode: single
- id: '1637607890867'
  alias: Switch Bedroom Off
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_bedroom_off
    event_data:
      id: dimmer_switch_bedroom
      event: 4000
  condition: []
  action:
  - type: turn_off
    device_id: a88c31e33af2f4c62bf180b8b5dfbd86
    entity_id: light.color_temperature_light_14
    domain: light
  mode: single
- id: '1637607982482'
  alias: Switch Bedroom Dim Up
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_bedroom_dim_up
    event_data:
      id: dimmer_switch_bedroom
      event: 2000
  condition: []
  action:
  - device_id: a88c31e33af2f4c62bf180b8b5dfbd86
    domain: light
    entity_id: light.color_temperature_light_14
    type: brightness_increase
  mode: single
- id: '1637608013547'
  alias: Switch Bedroom Dim Down
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_bedroom_dim_down
    event_data:
      id: dimmer_switch_bedroom
      event: 3000
  condition: []
  action:
  - device_id: a88c31e33af2f4c62bf180b8b5dfbd86
    domain: light
    entity_id: light.color_temperature_light_14
    type: brightness_decrease
  mode: single
- id: '1637608281692'
  alias: Switch Bedroom On
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_bedroom_on
    event_data:
      id: dimmer_switch_bedroom
      event: 1000
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.color_temperature_light_14
    data:
      kelvin: 2700
      brightness_pct: 100
  mode: single
- id: '1638103067320'
  alias: Fridge Door Open
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: f46ce8be912189b4f630e8d0b2d8396e
    entity_id: binary_sensor.openclose_23
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    id: fridge_door_open
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.kitchen_speaker
      message: Please close the fridge
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.turn_off
    target:
      entity_id: media_player.kitchen_speaker
  mode: single
- id: '1638660021716'
  alias: Reset TV volume
  description: In case another volume got turned down and TV volume too far up. Reset
    TV volume to encourage not using other volume
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    id: livingroomtv_sourcechange
    attribute: source
  condition: []
  action:
  - service: media_player.volume_set
    target:
      entity_id: media_player.living_room_tv
    data:
      volume_level: 0.1
  mode: single
- id: '1638819876867'
  alias: Freezer Door Open
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: cdefbd90cd630be260a0e4431d1a3df6
    entity_id: binary_sensor.openclose_24
    domain: binary_sensor
    id: freezer_door_open
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.kitchen_speaker
      message: Please close the freezer
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.turn_off
    target:
      entity_id: media_player.kitchen_speaker
  mode: single
- id: '1641937478771'
  alias: Keep hallway lights dimmed
  description: ''
  trigger:
  - platform: state
    entity_id: light.hallway_lights
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 90
    target:
      entity_id: light.hallway_lights
  mode: single
- id: '1641938129788'
  alias: Turn on kitchen light on motion in kitchen
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.tradfri_motion_sensor_2
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.kitchen_lights
    state: 'off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights
    data:
      transition: 3
  mode: single
- id: '1642070225995'
  alias: Keep dining table lights dimmed
  description: ''
  trigger:
  - platform: state
    entity_id: light.dining_table_lamp
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 80
    target:
      entity_id: light.dining_table_lamp
  mode: single
- id: '1643575469299'
  alias: Storage room light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.tradfri_motion_sensor
      light_target:
        entity_id: light.dimmable_light_16
- id: '1647899713913'
  alias: Switch Hallway Off
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_hallway_off
    event_data:
      id: on_off_switch_hallway
      event: 2002
  condition: []
  action:
  - service: script.turn_off_most_things
    data: {}
  mode: single
- id: '1647899869741'
  alias: Switch Hallway On
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    id: switch_hallway_on
    event_data:
      id: on_off_switch_hallway
      event: 1002
  condition: []
  action:
  - service: script.turn_on_some_things
    data: {}
  mode: single
- id: '1670063956996'
  alias: Sunset turn on Winter lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.on_off_plug_in_unit_12
  mode: single
- id: '1670064004871'
  alias: Sunrise turn off winter lights
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.on_off_plug_in_unit_12
  mode: single
- id: '1670843922251'
  alias: Hit table, turn on lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.vibration_49
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.dining_table_lamp
  mode: single
- id: '1672787107393'
  alias: Turn off kitchen speaker when tv turns on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.living_room_tv
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.kitchen_speaker
  mode: single
- id: '1677009537327'
  alias: Coming home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: script.turn_on_some_things
    data: {}
  mode: single
- id: '1677009613653'
  alias: Leaving home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    to: '0'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: script.turn_off_most_things
    data: {}
  - if:
    - condition: time
      before: '10:00:00'
      weekday:
      - sun
      - sat
      - fri
      - thu
      - wed
      - tue
      - mon
    then:
    - service: dreame_vacuum.vacuum_clean_segment
      data:
        segments:
        - 6
        - 8
        suction_level: 4
      target:
        entity_id: vacuum.dreame
  mode: single
- id: '1678609388231'
  alias: Door handle notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.vibration_50
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_s22_ultra_app
    data:
      message: Door handle moved
  mode: single
- id: '1680435135244'
  alias: Vacuum wednesdays
  description: ''
  trigger:
  - platform: time
    at: '13:00:00'
  condition:
  - condition: time
    weekday:
    - wed
    after: 00:00:00
    before: 00:00:00
  action:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      suction_level: 4
      segments: {}
    target:
      entity_id: vacuum.dreame
  mode: single
- id: '1680599724180'
  alias: Bird notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - image_processing.birds
    from: '0'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: notify.mobile_app_s22_ultra_app
    data:
      title: "Birds! \U0001F426"
      data:
        image: /api/camera_proxy/camera.birds
      message: Motion detected!
  - service: notify.mobile_app_galaxy_s10e
    data:
      message: Motion detected!
      title: "Birds! \U0001F426"
      data:
        image: /api/camera_proxy/camera.birds
  mode: single
- id: '1681828538059'
  alias: Stove hood moisture alert
  description: ''
  trigger:
  - platform: template
    value_template: '{{ (states(''sensor.kitchen_hood_2'') | int) > 68 }}'
  condition: []
  action:
  - service: tts.cloud_say
    data:
      cache: false
      entity_id: media_player.kitchen_speaker
      message: High moisture over stove
  mode: single
