# Of course not the actual secrets, just a list of what's needed.
# Rename this file to secrets.yaml and replace placeholders with actual values
tibber_token: placeholder
entsoe_command: "pwsh /config/pwsh/ENTSO-E.ps1 placeholder"